Repository kpn678/fitlit, pull requests merged in 2022-05, with the labels that each got.

#26 Feature/sleep class and testing
  src/Sleep.js
  src/User.js
  test/Hydration-test.js
  test/Sleep-test.js
  test/User-test.js
Labels: Enhancement

#25 Feature/add icons to app
  dist/index.html
  src/css/styles.css
  src/images/belit-logo.png
  src/images/post.png
  src/images/user.png
  src/scripts.js
Labels: UX / UI

#28 Feature/weekly dashboard display
  dist/index.html
  src/Hydration.js
  src/Sleep.js
  src/css/styles.css
  src/scripts.js
  test/Hydration-test.js
  test/Sleep-test.js
Labels: DOM Manipulation

#39 Feature/all time sleep info display
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: Enhancement

#40 Docs/update readme
  README.md
Labels: Documentation
